### ISSUE TITLE
Build a ready-made VM with CVE Server installed and setup or make a simple install script

### ISSUE THREAD

**Issue by claudijd** [SpiderLabs/cve_server#15]
I think we can really drive adoption and interest in the CVE server project if we simply provide a ready-made VM with the CVE server installed.  Alternatively, what if you could provide an installation/setup script that made it dirt simple for someone to take a vanilla Ubuntu build and "curl path | bash" for a guided install.

I think this is the one missing link to getting people really excited about using this internally.

I'm also willing to help if you guys haven't already started pursuing this or have interest in doing it yourselves.

*HUGS*

**Comment by pwnbus** [comment]
I'm a little hesitant to create a VM and try to host it somewhere and whatnot, I think a installation/setup script is the route to go here. If you're feeling up to the task, feel free. If not, we'll probably pick up this task in the next couple of weeks for one of the hack days. 

Thanks for the feedback, Mr. Claudius!
(hug)
