### ISSUE TITLE
Error in installation phase

### ISSUE THREAD

**Issue by ehsanmostajeran** [SpiderLabs/cve_server#29]
Hi, nice work.
I am setting up this server, I am getting this error, meanwhile server itself working when I check with CVE.

Uncompressing /root/cve_server/lib/cve_server/../../nvd_data/nvdcve-2002.xml.gz
Exporting data into the CVE collection
/usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:165:in `evaluate': Undefined namespace prefix: .//vuln:summary (Nokogiri::XML::XPath::SyntaxError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:165:in `block in xpath'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:156:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:156:in `xpath'
        from /root/cve_server/lib/cve_server/nvd/entry.rb:30:in `xpath_content'
        from /root/cve_server/lib/cve_server/nvd/entry.rb:16:in `to_hash'
        from /root/cve_server/lib/cve_server/nvd/reader.rb:17:in `block in all_cve'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
        from /root/cve_server/lib/cve_server/nvd/reader.rb:16:in `collect'
        from /root/cve_server/lib/cve_server/nvd/reader.rb:16:in `all_cve'
        from ./bin/seed:18:in `block in <main>'
        from ./bin/seed:13:in `each'
        from ./bin/seed:13:in `<main>'
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: production
* Daemonizing...

Thanks in advance

**Comment by karmatr0n** [comment]
Hi, it seems the nvd_downloader is having issues to download just the version 2 NVD reports. We will fix that as soon as possible, thanks for your report.

**Comment by karmatr0n** [comment]
We have merged a patch into the master branch a patch to fix this issue, get this new code and please remove the files inside the nvd_data directory.  That should fix the issue.

Thanks
