### ISSUE TITLE
Start using Travis-CI for unit-test coverage

### ISSUE THREAD

**Issue by claudijd** [SpiderLabs/cve_server#34]
travis ci is pretty handy for public projects like this, just add a .travis file and have an org admin enable it on the repo.  This will mean that new PRs will automatically be run against the unit-tests and will report in the PR request.

**Comment by claudijd** [comment]
PS - let me know if you want to chat offline or need help

**Comment by karmatr0n** [comment]
Hi, 

This is a great idea. I added a initial draft for the .travis.yml file.  I will do PR right now.
